version: "3.3"

networks:
  dokploy-network:
    external: true

services:
  db:
    platform: linux/x86_64
    image: mysql:latest
    volumes:
      - /Volumes/Etc2/docker/clim_profi
    restart: always
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: zX3aN9tT0vdZ3f
      MYSQL_DATABASE: klimsystems
      MYSQL_PASSWORD: zX3aN9tT0vdZ3f
    networks:
      - dokploy-network

  phpmyadmin:
    platform: linux/x86_64
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      DB: klimsystems
      MYSQL_ROOT_PASSWORD: zX3aN9tT0vdZ3f
    networks:
      - dokploy-network

  php:
    build:
      context: .
      dockerfile: 'docker/php/Dockerfile'
    links:
      - db
    volumes:
      - ./docker/php/api:/var/www/klimsystems/:rw
    networks:
      - dokploy-network


  test:
    image: nginx:latest
    volumes:
      - './docker/php/api:/var/www/klimsystems'
      - './docker/admin:/var/www/admin'
      - './docker/site:/var/www/public'
      - './docker/nginx/test/conf.d:/etc/nginx/conf.d'
    links:
      - php
    ports:
      - '3001:80'
      - '3002:443'
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true